module InlinePartial
  VERSION: String

  module Helper
    @_inline_partials: Hash[(Symbol | String), ^(*untyped) -> untyped]

    def inline_partial: ((Symbol | String)) { (*untyped) -> untyped } -> nil

    def render_inline_partial: ((Symbol | String), ?Object, ?collection: Array[untyped]) -> String

    private

    def safe_join: (Array[untyped]) -> untyped
    def capture: (untyped) { (*untyped) -> untyped } -> untyped
  end

  class Railtie
    def self.initializer: (String) { () -> void } -> void
  end
end

module Rails
  class Railtie
    def self.initializer: (String) { () -> void } -> void
  end
end

module ActiveSupport
  def self.on_load: (Symbol) { () -> void } -> void
end
